spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    database-platform: org.hibernate.dialect.MySQL5Dialect




#org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

mybatis:
  type-aliases-package: com.example.demo.mybatisDemo.entity
  mapper-locations: classpath:mapper/*/*.xml   #classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    default-statement-timeout: 25000
    default-executor-type: reuse
    map-underscore-to-camel-case: true
